# Generated by Django 3.2.11 on 2022-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_writerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprofile',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
