# Generated by Django 3.2.11 on 2022-10-23 14:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
